Repository brstu/OTIS-2024, pull requests merged in 2024-11, with the labels that each got.

#84 [task_04] Add lab4
  readme.md
  trunk/ii02614/task_04/doc/image1.jpg
  trunk/ii02614/task_04/doc/image2.jpg
  trunk/ii02614/task_04/doc/image3.jpg
  trunk/ii02614/task_04/doc/report.md
Labels: II-26

#53 [task_02] Add lab2
  readme.md
  trunk/ii230205/task2/doc/readme.md
  trunk/ii230205/task2/src/CMakeLists.txt
  trunk/ii230205/task2/src/task-2.cpp
Labels: II-26, Not marked in the table

#80 [task_02] Lab_02
  readme.md
  trunk/ii02625/task_02/doc/readme.md
  trunk/ii02625/task_02/doc/unliner.png
  trunk/ii02625/task_02/src/CMakeLists.txt
  trunk/ii02625/task_02/src/task_02.cpp
Labels: II-26

#81 [task_03] Lab_03
  readme.md
  trunk/ii02625/task_03/doc/add_adjes.png
  trunk/ii02625/task_03/doc/add_vertex.png
  trunk/ii02625/task_03/doc/change_weight.png
  trunk/ii02625/task_03/doc/eulerian_path.png
  trunk/ii02625/task_03/doc/readme.md
  trunk/ii02625/task_03/src/CMakeLists.txt
  trunk/ii02625/task_03/src/OTIS3.cpp
Labels: II-26

#34 [task_01] Add task solution
  readme.md
  trunk/ii02621/task_01/doc/Readme.md
  trunk/ii02621/task_01/doc/image.png
  trunk/ii02621/task_01/src/CMakeLists.txt
  trunk/ii02621/task_01/src/OTIS1LAB.cpp
Labels: II-26, scr directory :grin:

#82 [task_02] Add task solution lab2
  readme.md
  trunk/ii02621/task_02/doc/Readme.md.txt
  trunk/ii02621/task_02/doc/unliner.png
  trunk/ii02621/task_02/src/CMakeLists.txt
  trunk/ii02621/task_02/src/отис2лаба.cpp
Labels: II-26

#44 [task_01] Lab1
  readme.md
  trunk/ii-230276/task_01/doc/readme.md
  trunk/ii-230276/task_01/src/CMakeLists.txt
  trunk/ii-230276/task_01/src/Source.cpp
Labels: II-25

#68 [task_04] Lab4
  readme.md
  trunk/ii02612/task_04/doc/nika1.png
  trunk/ii02612/task_04/doc/nika2.png
  trunk/ii02612/task_04/doc/nika3.png
  trunk/ii02612/task_04/doc/nika4.png
  trunk/ii02612/task_04/doc/readme.md
Labels: II-26

#77 [task_02] Add task solution 2labaOTIS
  readme.md
  trunk/ii02619/task_02/doc/Readme.md.txt
  trunk/ii02619/task_02/doc/unliner.png
  trunk/ii02619/task_02/src/CMakeLists.txt
  trunk/ii02619/task_02/src/OTISlaba2.cpp
Labels: II-26

#87 [task_02] Add lab2
  readme.md
  trunk/II02513/task01/src/readme.md
  trunk/II02513/task_02/doc/readme.md
  trunk/II02513/task_02/doc/unliner.png
  trunk/II02513/task_02/src/CMakeLists.txt
  trunk/II02513/task_02/src/qwerty.cpp
Labels: II-25

#89 [task_04] Add lab4
  readme.md
  trunk/ii02513/task_04/doc/image1.jpg
  trunk/ii02513/task_04/doc/image2.jpg
  trunk/ii02513/task_04/doc/image3.jpg
  trunk/ii02513/task_04/doc/report.md
Labels: II-25

#93 [task_01] Add task solution
  readme.md
  trunk/ii002601/task_01/doc/graphics.png
  trunk/ii002601/task_01/doc/readme.md
  trunk/ii002601/task_01/src/CMakeLists.txt
  trunk/ii002601/task_01/src/otis1.cpp
Labels: II-26

#69 [task_01] Add task solution 1labaOTIS
  trunk/ii02610/task_01/doc/Readme.md
  trunk/ii02610/task_01/doc/image.png
  trunk/ii02610/task_01/src/CMakeLists.txt
  trunk/ii02610/task_01/src/Lab1OTIS.cpp
Labels: II-26, Not marked in the table

#78 [task_02] Add task solution
  trunk/ii02610/task_02/doc/Readme.md
  trunk/ii02610/task_02/doc/unliner.png
  trunk/ii02610/task_02/src/CMakeLists.txt
  trunk/ii02610/task_02/src/LAB2OTIS.cpp
Labels: II-26, Not marked in the table

#95 [task_03] GraphApp
  readme.md
  trunk/ii00230308/task3/doc/readme.md
  trunk/ii00230308/task3/src/CMakeLists.txt
  trunk/ii00230308/task3/src/GraphApp.cpp
Labels: invalid, II-26

#96 [task_04] Add task solution
  readme.md
  trunk/ii02602/task_04/doc/Readme.md
  trunk/ii02602/task_04/doc/picture1.png
  trunk/ii02602/task_04/doc/picture2.png
  trunk/ii02602/task_04/doc/picture3.png
  trunk/ii02602/task_04/doc/picture4.png
Labels: II-26

#97 [task_02] Add task solution
  readme.md
  trunk/ii002601/task_02/doc/otis.png
  trunk/ii002601/task_02/doc/readme.md
  trunk/ii002601/task_02/src/CMakeLists.txt
  trunk/ii002601/task_02/src/otis2.cpp
Labels: wontfix, II-26

#101 [task_04] Add task solution
  readme.md
  trunk/ii002601/task_04/nika_1.png
  trunk/ii002601/task_04/nika_2.png
  trunk/ii002601/task_04/nika_3.png
  trunk/ii002601/task_04/nika_4.png
  trunk/ii002601/task_04/readme.md
Labels: II-26

#91 [task_03] Add task solution
  readme.md
  trunk/ii02610/task_03/doc/img1.png
  trunk/ii02610/task_03/doc/img10.png
  trunk/ii02610/task_03/doc/img2.png
  trunk/ii02610/task_03/doc/img3.png
  trunk/ii02610/task_03/doc/img4.png
  trunk/ii02610/task_03/doc/img5.png
  trunk/ii02610/task_03/doc/img6.png
  trunk/ii02610/task_03/doc/img7.png
  trunk/ii02610/task_03/doc/img8.png
  trunk/ii02610/task_03/doc/img9.png
  trunk/ii02610/task_03/doc/report.md
  trunk/ii02610/task_03/src/CMakeLists.txt
  trunk/ii02610/task_03/src/main.py
  trunk/ii02610/task_03/src/main2.cpp
Labels: II-26

#90 [task_04] Add task solution
  readme.md
  trunk/ii02610/task_04/doc/Readme.md
  trunk/ii02610/task_04/doc/task401.jpg
  trunk/ii02610/task_04/doc/task402.jpg
  trunk/ii02610/task_04/doc/task403.jpg
  trunk/ii02610/task_04/doc/task404.jpg
  trunk/ii02610/task_04/doc/task405.jpg
Labels: question, II-26

#98 [task_02] Solution
  readme.md
  trunk/ii00230304/task2/doc/graph.png
  trunk/ii00230304/task2/doc/report.md
  trunk/ii00230304/task2/src/CMakeLists.txt
  trunk/ii00230304/task2/src/task_02.cpp
Labels: II-26

#108 [task_01] Add task solution 1labaOTIS
  readme.md
  trunk/ii02616/task_01/doc/Readme.md.txt
  trunk/ii02616/task_01/doc/graphic.png
  trunk/ii02616/task_01/src/1labasOTIS.cpp
  trunk/ii02616/task_01/src/CMakeLists.txt
Labels: II-26

#109 [task_02] Add task solution 2labOTIS
  readme.md
  trunk/ii02616/task_02/doc/Readme.md
  trunk/ii02616/task_02/doc/graphic.png
  trunk/ii02616/task_02/src/2labasOTIS.cpp
  trunk/ii02616/task_02/src/CMakeLists.txt
Labels: II-26

#111 [task_04] Add task solution 4labasOTIS
  readme.md
  trunk/ii02616/task_04/doc/Readme.md
  trunk/ii02616/task_04/doc/task041.png
  trunk/ii02616/task_04/doc/task042.png
  trunk/ii02616/task_04/doc/task043.png
  trunk/ii02616/task_04/doc/task044.png
  trunk/ii02616/task_04/doc/task045.png
  trunk/ii02616/task_04/doc/task046.png
Labels: II-26

#113 [task_04] Add task solution 4lab
  readme.md
  trunk/ii02618/task_04/doc/Readme.md
Labels: II-26

#32 [task_01] Add task solution
  readme.md
  trunk/ii02509/trunk/task_01/document/graphics.png
  trunk/ii02509/trunk/task_01/document/readme.md
  trunk/ii02509/trunk/task_01/src/1LabOTIS.sln
  trunk/ii02509/trunk/task_01/src/CMakeLists.txt
Labels: II-25

#118 [task_04] Lab4
  readme.md
  trunk/ii02621/task_04/doc/Readme.md
  trunk/ii02621/task_04/doc/task041.png
  trunk/ii02621/task_04/doc/task042.png
  trunk/ii02621/task_04/doc/task043.png
  trunk/ii02621/task_04/doc/task044.png
  trunk/ii02621/task_04/doc/task045.png
  trunk/ii02621/task_04/doc/task046.png
Labels: Not marked in the table

#147 [task_03] Sukhovilo Solution
  readme.md
  trunk/ii02618/task_03/doc/add_adjes.png
  trunk/ii02618/task_03/doc/add_vertex.png
  trunk/ii02618/task_03/doc/change_weight.png
  trunk/ii02618/task_03/doc/eulerian_path.png
  trunk/ii02618/task_03/doc/readme.md
  trunk/ii02618/task_03/src/CMakeLists.txt
  trunk/ii02618/task_03/src/OTIS3.cpp
Labels: II-26

#146 [task_03] Solution
  readme.md
  trunk/ii00230304/task3/doc/report.md
  trunk/ii00230304/task3/src/CMakeLists.txt
  trunk/ii00230304/task3/src/lab3.cpp
Labels: II-26

#128 [task_01] Add task solution
  readme.md
  trunk/ii0230289/task01/doc/Readme.md
  trunk/ii0230289/task01/doc/graphics.png
  trunk/ii0230289/task01/src/CMakeLists.txt
  trunk/ii0230289/task01/src/otis1.cpp
Labels: bug

#156 [task_03] Add task solution Lab3
  readme.md
  trunk/ii02606/task_03/doc/Add_color.png
  trunk/ii02606/task_03/doc/Add_edge.png
  trunk/ii02606/task_03/doc/Add_vertex.png
  trunk/ii02606/task_03/doc/Change_color.png
  trunk/ii02606/task_03/doc/Change_name.png
  trunk/ii02606/task_03/doc/Change_weight.png
  trunk/ii02606/task_03/doc/Delete.png
  trunk/ii02606/task_03/doc/Euler_path.png
  trunk/ii02606/task_03/doc/Move.png
  trunk/ii02606/task_03/doc/Readme.md
  trunk/ii02606/task_03/doc/Shortest_Path.png
  trunk/ii02606/task_03/doc/Windows.png
  trunk/ii02606/task_03/src/3labaOTIS.cpp
  trunk/ii02606/task_03/src/CMakeLists.txt
Labels: II-26

#149 [task_03] Add task solution
  readme.md
  trunk/ii02619/task_03/doc/add_adjes.png
  trunk/ii02619/task_03/doc/add_vertex.png
  trunk/ii02619/task_03/doc/change_weight.png
  trunk/ii02619/task_03/doc/eulerian_path.png
  trunk/ii02619/task_03/doc/readme.md
  trunk/ii02619/task_03/src/3labotis.cpp
  trunk/ii02619/task_03/src/CMakeLists.txt
Labels: invalid

#171 [task_04] Solution
  readme.md
  trunk/ii00230304/task4/doc/picture1.png
  trunk/ii00230304/task4/doc/picture2.png
  trunk/ii00230304/task4/doc/picture3.png
  trunk/ii00230304/task4/doc/readme.md
Labels: II-26

#169 [task_04] My solution
  readme.md
  trunk/ii230288/task04/doc/readme.md
  trunk/ii230288/task04/doc/task4(1).png
  trunk/ii230288/task04/doc/task4(2).png
  trunk/ii230288/task04/doc/task4(3).png
  trunk/ii230288/task04/doc/task4(4).png
  trunk/ii230288/task04/doc/task4(5).png
  trunk/ii230288/task04/doc/task4(6).png
Labels: II-25
