Repository brstu/OTIS-2024, pull requests merged in 2024-12, with the labels that each got.

#183 [task_02] Add task solution
  readme.md
  trunk/ii02527/task_02/doc/readme.md
  trunk/ii02527/task_02/src/CMakeLists.txt
  trunk/ii02527/task_02/src/main.cpp
Labels: good first issue

#196 [task_03] Add task solution
  readme.md
  trunk/ii02527/task_03/doc/readme.md
  trunk/ii02527/task_03/src/CMakeLists.txt
  trunk/ii02527/task_03/src/lab03.cpp
  trunk/ii02527/task_03/src/main.py
Labels: II-25

#204 [task_04] Add problem solution
  readme.md
  trunk/ii02611/task_04/doc/ohio1.png
  trunk/ii02611/task_04/doc/ohio2.png
  trunk/ii02611/task_04/doc/ohio3.png
  trunk/ii02611/task_04/doc/ohio4.png
  trunk/ii02611/task_04/doc/readme.md
Labels: II-26

#205 [task_04] Add task solution 4laba
  readme.md
  trunk/ii02604/task_04/doc/image1.png
  trunk/ii02604/task_04/doc/image2.png
  trunk/ii02604/task_04/doc/image3.png
  trunk/ii02604/task_04/doc/report.md
Labels: II-26

#167 [task_03] Lab3
  trunk/ii002601/task_03/doc/1img.png
  trunk/ii002601/task_03/doc/2img.png
  trunk/ii002601/task_03/doc/3img.png
  trunk/ii002601/task_03/doc/4img.png
  trunk/ii002601/task_03/doc/5img.png
  trunk/ii002601/task_03/doc/6img.png
  trunk/ii002601/task_03/doc/7img.png
  trunk/ii002601/task_03/doc/8img.png
  trunk/ii002601/task_03/doc/readme.md
  trunk/ii002601/task_03/src/CMakeLists.txt
  trunk/ii002601/task_03/src/otis3.cpp
Labels: II-26

#197 [task_04] Add task solution
  readme.md
  trunk/ii02527/task_04/doc/1.jpg
  trunk/ii02527/task_04/doc/2.jpg
  trunk/ii02527/task_04/doc/3.jpg
  trunk/ii02527/task_04/doc/readme.md
Labels: II-25

#209 [task_03] Add task solution lab3 otis
  readme.md
  trunk/ii02604/task_03/doc/image1.png
  trunk/ii02604/task_03/doc/image2.png
  trunk/ii02604/task_03/doc/image3.png
  trunk/ii02604/task_03/doc/image4.png
  trunk/ii02604/task_03/doc/image5.png
  trunk/ii02604/task_03/doc/image6.png
  trunk/ii02604/task_03/doc/image7.png
  trunk/ii02604/task_03/doc/image8.png
  trunk/ii02604/task_03/doc/report.md
  trunk/ii02604/task_03/src/CMakeLists.txt
  trunk/ii02604/task_03/src/OTISlab3.cpp
Labels: II-26

#210 [task_04] Solve task_04
  readme.md
  trunk/ii02613/task_04/doc/LAB4_pic1.png
  trunk/ii02613/task_04/doc/LAB4_pic2.png
  trunk/ii02613/task_04/doc/LAB4_pic3.png
  trunk/ii02613/task_04/doc/LAB4_pic4.png
  trunk/ii02613/task_04/doc/readme.md
Labels: II-26

#211 [task_05] Add task solution
  readme.md
  trunk/ii02506/task_05/doc/1.png
  trunk/ii02506/task_05/doc/2.png
  trunk/ii02506/task_05/doc/3.png
  trunk/ii02506/task_05/doc/report.md
Labels: II-25

#223 [task_04] Lab4
  trunk/ii02625/task_04/doc/image1.jpg
  trunk/ii02625/task_04/doc/image2.jpg
  trunk/ii02625/task_04/doc/image3.jpg
  trunk/ii02625/task_04/doc/report.md
Labels: II-26

#234 [task_04] Add task solution Lab4
  trunk/ii230205/task4/doc/img1.png
  trunk/ii230205/task4/doc/img2.png
  trunk/ii230205/task4/doc/img3.png
  trunk/ii230205/task4/doc/img4.png
  trunk/ii230205/task4/doc/img5.png
  trunk/ii230205/task4/doc/img6.png
  trunk/ii230205/task4/doc/readme.md
Labels: II-26

#244 [task_05] Solution
  readme.md
  trunk/ii00230308/task5/doc/report.md
  trunk/ii00230308/task5/doc/report.png
Labels: II-26

#245 [task_05] My solution
  readme.md
  trunk/ii230288/task05/doc/problem.png
  trunk/ii230288/task05/doc/report.md
Labels: II-25

#227 [doc] Update readme.md
  readme.md
Labels: documentation, help wanted, question, II-25

#267 [task_05] Add task solution
  readme.md
  trunk/ii230324/task_05/doc/1.png
  trunk/ii230324/task_05/doc/2.png
  trunk/ii230324/task_05/doc/3.png
  trunk/ii230324/task_05/doc/report.md
Labels: II-26

#269 [task_03] Add task solution
  trunk/ii02602/task_03/doc/1.png
  trunk/ii02602/task_03/doc/2.png
  trunk/ii02602/task_03/doc/3.png
  trunk/ii02602/task_03/doc/4.png
  trunk/ii02602/task_03/doc/readme.md
  trunk/ii02602/task_03/src/CMakeLists.txt
  trunk/ii02602/task_03/src/OTIS_03.cpp
Labels: II-26

#272 [task_02] Add Solution
  trunk/ii0230326/task_02/doc/readme.md
  trunk/ii0230326/task_02/doc/графики нелинейных моделей.png
  trunk/ii0230326/task_02/src/CMakeLists.txt
  trunk/ii0230326/task_02/src/task_02.cpp
Labels: II-26

#274 [task_03] Add task solution
  trunk/ii0230205/task_03/doc/image-1.png
  trunk/ii0230205/task_03/doc/image-2.png
  trunk/ii0230205/task_03/doc/image-3.png
  trunk/ii0230205/task_03/doc/image-4.png
  trunk/ii0230205/task_03/doc/image-5.png
  trunk/ii0230205/task_03/doc/image-6.png
  trunk/ii0230205/task_03/doc/image.png
  trunk/ii0230205/task_03/doc/readme.md
  trunk/ii0230205/task_03/src/CMakeLists.txt
  trunk/ii0230205/task_03/src/task_03.cpp
Labels: II-26

#277 [task_04] Add_lab4
  readme.md
  trunk/ii0230326/task_04/1.jpg
  trunk/ii0230326/task_04/2.jpg
  trunk/ii0230326/task_04/3.jpg
  trunk/ii0230326/task_04/4.jpg
  trunk/ii0230326/task_04/5.jpg
  trunk/ii0230326/task_04/6.jpg
  trunk/ii0230326/task_04/readme.md
Labels: II-26

#278 [task_03] Add task solution
  readme.md
  trunk/ii0230289/task03/doc/1.png
  trunk/ii0230289/task03/doc/2.png
  trunk/ii0230289/task03/doc/3.png
  trunk/ii0230289/task03/doc/4.png
  trunk/ii0230289/task03/doc/readme.md
  trunk/ii0230289/task03/src/CMakeLists.txt
  trunk/ii0230289/task03/src/task_03.cpp
Labels: II-25

#287 [task_04] Solution
  trunk/ii0230279/task_04/doc/Readme.md
  trunk/ii0230279/task_04/doc/task401.jpg
  trunk/ii0230279/task_04/doc/task402.jpg
  trunk/ii0230279/task_04/doc/task403.jpg
  trunk/ii0230279/task_04/doc/task404.jpg
  trunk/ii0230279/task_04/doc/task405.jpg
Labels: II-25

#288 [task_04] Solution
  readme.md
  trunk/ii0230289/task04/doc/Readme.md
  trunk/ii0230289/task04/doc/picture1.png
  trunk/ii0230289/task04/doc/picture2.png
  trunk/ii0230289/task04/doc/picture3.png
  trunk/ii0230289/task04/doc/picture4.png
Labels: II-25

#300 [doc] Update main table (readme.md)
  readme.md
Labels: documentation, II-26

#296 [task_02] Add task solution
  trunk/ii02622/task_02/doc/otis.png
  trunk/ii02622/task_02/doc/readme.md
  trunk/ii02622/task_02/src/CMakeLists.txt
  trunk/ii02622/task_02/src/otis2.cpp
Labels: II-26

#297 [task_01] Add task solution
  readme.md
  trunk/ii02622/task_01/doc/Readme.md
  trunk/ii02622/task_01/doc/graphics.png
  trunk/ii02622/task_01/scr/1-LAB-OTIS.cpp
  trunk/ii02622/task_01/scr/CMakeLists.txt
Labels: II-26

#299 [task_03] Add task solution
  trunk/ii02622/task_03/doc/1img.png
  trunk/ii02622/task_03/doc/2img.png
  trunk/ii02622/task_03/doc/3img.png
  trunk/ii02622/task_03/doc/4img.png
  trunk/ii02622/task_03/doc/5img.png
  trunk/ii02622/task_03/doc/6img.png
  trunk/ii02622/task_03/doc/7img.png
  trunk/ii02622/task_03/doc/8img.png
  trunk/ii02622/task_03/doc/readme.md
  trunk/ii02622/task_03/src/CMakeLists.txt
  trunk/ii02622/task_03/src/otis3.cpp
Labels: II-26

#306 [task_01] Add task solution
  readme.md
  trunk/ii02626/lab_01/doc/readme.md
  trunk/ii02626/lab_01/src/CMakeLists.txt
  trunk/ii02626/lab_01/src/main.cpp
Labels: help wanted, II-26

#307 [task_02] Add task solution
  readme.md
  trunk/ii02626/lab_02/doc/readme.md
  trunk/ii02626/lab_02/src/CMakeLists.txt
  trunk/ii02626/lab_02/src/main.cpp
Labels: help wanted, II-26

#309 [task_03] Add task solution
  readme.md
  trunk/ii02626/lab_03/doc/readme.md
  trunk/ii02626/lab_03/src/CMakeLists.txt
  trunk/ii02626/lab_03/src/main.cpp
  trunk/ii02626/lab_03/src/main.py
Labels: help wanted, II-26

#310 [task_04] Add task solution
  readme.md
  trunk/ii02626/task_04/doc/1.jpg
  trunk/ii02626/task_04/doc/2.jpg
  trunk/ii02626/task_04/doc/3.jpg
  trunk/ii02626/task_04/doc/readme.md
Labels: help wanted, II-26
