Repository brstu/OTIS-2024, pull requests merged in 2024-10, with the labels that each got.

#19 [task_01] Add lab task 01
  readme.md
  trunk/ii02605/task_01/doc/graphics.png
  trunk/ii02605/task_01/doc/readme.md
  trunk/ii02605/task_01/src/CMakeLists.txt
  trunk/ii02605/task_01/src/otis_lab_1.cpp
Labels: II-26

#13 [task_01] Modeling controlled object
  readme.md
  trunk/ii00230308/task1/doc/graphics.png
  trunk/ii00230308/task1/doc/readme.md
  trunk/ii00230308/task1/src/CMakeLists.txt
  trunk/ii00230308/task1/src/Source1.cpp
Labels: II-26

#18 [task_01] Add problem solution
  readme.md
  trunk/ii230324/task_01/doc/report.md
  trunk/ii230324/task_01/src/CMakeLists.txt
  trunk/ii230324/task_01/src/task_01.cpp
Labels: II-26

#35 [task_01] Add lab1
  readme.md
  trunk/ii230205/task 1/doc/readme.md
  trunk/ii230205/task 1/src/CMakeLists.txt
  trunk/ii230205/task 1/src/task-1.cpp
Labels: II-26

#41 [task_02] Add lab2
  readme.md
  trunk/ii230278/task_02/readme.md
  trunk/ii230278/task_02/src/CMakeLists.txt
  trunk/ii230278/task_02/src/main.cpp
Labels: II-25

#43 [task_01] Add lab01
  readme.md
  trunk/ii02527/task_01/doc/readme.md
  trunk/ii02527/task_01/src/CMakeLists.txt
  trunk/ii02527/task_01/src/main.cpp
Labels: II-25

#46 [task_02] Add task solution
  readme.md
  trunk/ii02612/task_02/doc/otis.png
  trunk/ii02612/task_02/doc/readme.md
  trunk/ii02612/task_02/src/CMakeLists.txt
  trunk/ii02612/task_02/src/task_02.cpp
Labels: II-26

#50 [task_02] Proportional-integral-differentiative controller
  readme.md
  trunk/ii00230308/task2/doc/graphics.png
  trunk/ii00230308/task2/doc/readme.md
  trunk/ii00230308/task2/src/CMakeLists.txt
  trunk/ii00230308/task2/src/lab2.cpp
Labels: II-26

#38 [task_02] Add task solution
  readme.md
  trunk/ii02608/task_02/doc/Readme.md
  trunk/ii02608/task_02/doc/unliner.png
  trunk/ii02608/task_02/src/2LabOTIS.cpp
  trunk/ii02608/task_02/src/CMakeLists.txt
Labels: II-26

#54 [task_01] Solution for lab1
  readme.md
  trunk/ii02611/task_01/doc/graphic.png
  trunk/ii02611/task_01/doc/readme.md
  trunk/ii02611/task_01/src/CMakeLists.txt
  trunk/ii02611/task_01/src/main.cpp
Labels: II-26

#55 [task_04] Add task solution
  readme.md
  trunk/ii02605/task_04/doc/report.md
  trunk/ii02605/task_04/doc/screen1.jpg
  trunk/ii02605/task_04/doc/screen2.jpg
  trunk/ii02605/task_04/doc/screen3.jpg
  trunk/ii02605/task_04/doc/screen4.jpg
Labels: II-26

#25 [task_01] Lab1
  readme.md
  trunk/ii02604/task_01/doc/imagegraf.png
  trunk/ii02604/task_01/doc/readme.md
  trunk/ii02604/task_01/src/1LabOTIS.cpp
  trunk/ii02604/task_01/src/CMakeLists.txt
Labels: II-26

#57 [task_02] Add lab2
  readme.md
  trunk/ii02602/task_02/doc/otis.png
  trunk/ii02602/task_02/doc/readme.md
  trunk/ii02602/task_02/src/CMakeLists.txt
  trunk/ii02602/task_02/src/task_02.cpp
Labels: II-26

#56 [task_01] Lab1 ii02613
  readme.md
  trunk/ii02613/task_01/doc/graph_OTIS_1.png
  trunk/ii02613/task_01/doc/readme.md
  trunk/ii02613/task_01/src/CMakeLists.txt
  trunk/ii02613/task_01/src/task_01.cpp
Labels: II-26

#52 [task_01] Add task solution number 1
  readme.md
  trunk/ii02606/task_01/doc/Readme.md
  trunk/ii02606/task_01/doc/image.png
  trunk/ii02606/task_01/src/1labaOTIS.cpp
  trunk/ii02606/task_01/src/CMakeLists.txt
Labels: II-26

#59 [task_04] Add task solution 4
  readme.md
  trunk/ii02608/task_04/doc/Readme.md
  trunk/ii02608/task_04/doc/task041.png
  trunk/ii02608/task_04/doc/task042.png
  trunk/ii02608/task_04/doc/task043.png
  trunk/ii02608/task_04/doc/task044.png
  trunk/ii02608/task_04/doc/task045.png
  trunk/ii02608/task_04/doc/task046.png
Labels: II-26

#65 [task_02] Lab2OTIS
  readme.md
  trunk/ii02604/task_02/doc/Readme.md
  trunk/ii02604/task_02/doc/grapfik.png
  trunk/ii02604/task_02/src/CMakeLists.txt
  trunk/ii02604/task_02/src/Lab2OTIS.cpp
Labels: II-26

#64 [task_02] Lab2 ii02613
  readme.md
  trunk/II02513/task_02/doc/Lab02_Graph.png
  trunk/II02513/task_02/doc/readme.md
  trunk/II02513/task_02/src/CMakeLists.txt
  trunk/II02513/task_02/src/task_02.cpp
Labels: II-26

#62 [task_02] Add lab2
  readme.md
  trunk/ii02606/task_02/doc/Readme.md
  trunk/ii02606/task_02/doc/unliner.png
  trunk/ii02606/task_02/src/2labaOTIS.cpp
  trunk/ii02606/task_02/src/CMakeLists.txt
Labels: II-26, Not marked in the table

#42 [task_01] Add lab1
  readme.md
  trunk/ii02525/task_01/src/CMakeLists.txt
  trunk/ii02525/task_01/src/Source.cpp
  trunk/ii02525/task_01/src/readme.md
Labels: II-25

#73 [task_02] Sollution
  readme.md
  trunk/ii02514/task02/doc/graphics.png
  trunk/ii02514/task02/doc/readme.md
  trunk/ii02514/task02/src/CMakeLists.txt
  trunk/ii02514/task02/src/lab2.cpp
Labels: II-25

#39 [task_01] Add lab1
  readme.md
  trunk/II-230284/task_01/doc/readme.md
  trunk/II-230284/task_01/src/CMakeLists.txt
  trunk/II-230284/task_01/src/Source.cpp
Labels: II-25

#67 [task_02] Solution for Lab2
  readme.md
  trunk/ii02611/task_02/doc/graphic.png
  trunk/ii02611/task_02/doc/readme.md
  trunk/ii02611/task_02/src/CMakeLists.txt
  trunk/ii02611/task_02/src/main.cpp
Labels: II-26
